---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-example-octodex
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: aws-example-octodex
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: aws-example-octodex
    spec:
      containers:
      - name: aws-example-octodex
        # image: 00000000000000.dkr.ecr.my-region.amazonaws.com/example-eks:tag
        image: 142943619081.dkr.ecr.us-east-1.amazonaws.com/example-eks:b9daeb12994afb2074b4c7e7e76eec54c5f2f456
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
